call plug#begin('~/.vim/plugged')
Plug 'lilydjwg/colorizer'
Plug 'scrooloose/nerdtree'
Plug 'vim-syntastic/syntastic'
Plug 'sirver/ultisnips'
Plug 'pbondoer/vim-42header'
Plug 'vim-airline/vim-airline'
Plug 'crusoexia/vim-monokai'
Plug 'honza/vim-snippets'
call plug#end()
